# Fallouts

A d6 list of fallouts when investigators encounter forces related to The Taker of Thoughts.

1. __Dissociative fugue:__ You are not the person you thought you were. Choose a new name, reroll your background, and reroll all optional investigator details you have. Choose one of your ability scores, roll d4 and add it to the score (max 18).
2. __Goosed:__ Goose feathers sprout from your body, plucking them is painful. You are an intimidating presence whilst amongst allies. Once during each round of combat you can remove one dice, after rolling, from an enemy who attacked an ally. When you are alone with no allies your HP is 0.
3. __Fingerprint ink:__ Thick ink exudes from your fingertips. It stops once it covers your prints but is excreted once more when removed through cleaning or use of the ink. Once a mystery write with the ink to predict the future or rewrite the past, doing so comes at a cost.
4. __Chromatophores:__ Invisible ethereal chromatophores surround your body (clothing included). With deep focus you can make these visible and control their colour, able to be used as camouflage and possible other uses.
5. __Expressive writing:__ You are constantly narrating events as they occur to you, whether on paper, out loud, or in your mind. This allows you to always self-distance yourself. +1 Stability.
6. __Rumpelstiltskin:__ Write down the true full name of a person or entity. The name is expunged from all realities except from the mind of its owner. Choose one of three effects: (1) the person/entity is bound to the current place they are located, (2) the person's/entity's nature is known to you (the facilitator shows the player its stat block), or (3) the person/entity suffers d12 CTRL damage.
