# Prelude

The below is a prelude that can be recitted to the players at the start of the mystery.


> An individual leads six others to a tree silhouetted by the setting sun. As she leads them she talks away her nerves. 
> The six only look ahead hearing her words not with meaning but as senseless noise. 
> Nevertheless she continues to create sounds. They respond in kind, with grunts, huffs, and whistles.
>
> As they reach the tree, engulfed by its shadow, they see their prize.
> A heavy tarnished bell hangs off a branch with a chain. The six instinctively circle it and talk and talk. 
> Their speech, full of jargon, overlaps and quickens into a cacophony, the meaning lost to their guide. 
> She promptly leaves, surely nothing strange will happen again. 
> But of course something will happen again, otherwise we wouldn’t be here. 
> And so, as she reaches the entrance of the Oxbury gardens she hears a massive unearthly gong from the bell. 
> She brings out her phone and rings a friend, hopefully her meaning won’t be lost through the panic in her voice.
