# Sticky Crawl

The Sticky Crawl is a method to create mystery locations with the following features:

- Locations are represented by sticky notes with 1-4 exits (matching the sticky note sides).
- The layout of the location is organic with random sticky notes being placed as the investigators use exits.
- The locations are not random, instead the “pool” of locations are bespoke to the mystery.

## Purpose

Why run or create a Sticky crawl instead of other methods?
Reasons includes:

- Sticky note areas are quick and interactive for the facilitator and players.
    - Facilitators do not need to print out a map. Instead, they draw each location on a sticky note as each location appears.
    - Players decide which ways to go in areas, therefore partially deciding how the location spreads out.
- Using ephemeral sticky notes intentianlly encourages an art style that is easy and quick to imitate.
    - As someone who's technical art skills are low it is nice to be able to make lo-fi images with purpose.

## How to run

Below is a brief summary of how to carry out a Sticky Crawl.

### Starting location

Once the investigators have entered the area set down the first location.
This may be a specific starting location or randomly chosen from the inital pool.

### Adding new locations

When a group of invstigators moves through an exit a location form a valid pool is added.
Genrally a new location is decided by rolling a dice matching the maximum number of locations in the pool.
If the location is not available choose the next available location in descending order (i.e. if you rolled a 4 which is not avialable choose number 3).

### Moving between locations

Investigators can move between locations with ortogonal adjacent exits.
Two locations whcih are orthogonla but have 0 or only one exits are not connected.

## Terminology

- __Area:__ This is the entire are of the mystery and is composed of all the locations.
- __Location:__ A location is one sticky note representing a location separate from other locations. A location could be a room, a set of connected rooms, a building, a city,  a forest, etc. The size of each location is dependant on the size of the area with each location in one area being around the same scale.
- __Exit:__ The exits are represented by lines on the sides of the sticky note location. 
The allow investigators to travel between locations.
When travelling between two locations the locations must be touching each other's sides and both the sides must have an exit.
The cinnection between two locations can be a door, a path, a road, etc.
- __Pool:__ A pool of locations is a set of locations that can be randomly drawn from.
A location on the table/in play is consdered not to be in the pool.
If a location is removed from the table/play it is returned to the pool.

## Example sticky crawls

- [Why doe the bell?](/the_toll_of_unmeaning/mystery_intro.qmd)

## Inspirations

- [Carcassonne by Klaus-Jürgen Wrede](https://boardgamegeek.com/boardgame/822/carcassonne)
- [Blue Prince by Dogubomb](https://en.wikipedia.org/wiki/Blue_Prince)
- Sticky MOnster by John Kenn Mortensen